export const SYSTEM_ORGANIZATION_ID = 'SYSTEM';

export const EvidenceActions = {
  PROVISION_ORGANIZATION: 'PROVISION_ORGANIZATION',
  DISABLE_ORGANIZATION: 'DISABLE_ORGANIZATION',
  PLATFORM_INTERVENTION: 'PLATFORM_INTERVENTION',
  ACTIVATE_ORGANIZATION: 'ACTIVATE_ORGANIZATION',
  INVITE_COLLABORATOR: 'INVITE_COLLABORATOR',
  ACCEPT_COLLABORATOR_INVITATION: 'ACCEPT_COLLABORATOR_INVITATION',
  RESEND_INVITATION: 'RESEND_INVITATION',
  REVOKE_INVITATION: 'REVOKE_INVITATION',
  UPDATE_COLLABORATOR_GRANTS: 'UPDATE_COLLABORATOR_GRANTS',
  SUSPEND_COLLABORATOR: 'SUSPEND_COLLABORATOR',
  REACTIVATE_COLLABORATOR: 'REACTIVATE_COLLABORATOR',
  REMOVE_COLLABORATOR: 'REMOVE_COLLABORATOR',
  PROMOTE_COLLABORATOR: 'PROMOTE_COLLABORATOR',
  PROPOSE_OWNERSHIP_TRANSFER: 'PROPOSE_OWNERSHIP_TRANSFER',
  ACCEPT_OWNERSHIP_TRANSFER: 'ACCEPT_OWNERSHIP_TRANSFER',
  CANCEL_OWNERSHIP_TRANSFER: 'CANCEL_OWNERSHIP_TRANSFER',
} as const;

