export const SYSTEM_ORGANIZATION_ID = 'SYSTEM';

export const EvidenceActions = {
  PROVISION_ORGANIZATION: 'PROVISION_ORGANIZATION',
  DISABLE_ORGANIZATION: 'DISABLE_ORGANIZATION',
  PLATFORM_INTERVENTION: 'PLATFORM_INTERVENTION',
  ACTIVATE_ORGANIZATION: 'ACTIVATE_ORGANIZATION',
  INVITE_COLLABORATOR: 'INVITE_COLLABORATOR',
  ACCEPT_COLLABORATOR_INVITATION: 'ACCEPT_COLLABORATOR_INVITATION',
  RESEND_INVITATION: 'RESEND_INVITATION',
  REVOKE_INVITATION: 'REVOKE_INVITATION',
  UPDATE_COLLABORATOR_GRANTS: 'UPDATE_COLLABORATOR_GRANTS',
} as const;

