export const SYSTEM_ORGANIZATION_ID = 'SYSTEM';

export const EvidenceActions = {
  PROVISION_ORGANIZATION: 'PROVISION_ORGANIZATION',
  DISABLE_ORGANIZATION: 'DISABLE_ORGANIZATION',
  PLATFORM_INTERVENTION: 'PLATFORM_INTERVENTION',
} as const;
